/* Gramatica.java */
/* Generated By:JavaCC: Do not edit this line. Gramatica.java */
import java.io.*;

class Gramatica implements GramaticaConstants {
  Tabelas Tabela = new Tabelas (); // Para o gerenciamento de variáveis
  public static void main (String[] args) throws ParseException
  {
   try
   {
    Gramatica analisador = new Gramatica (System.in);
    analisador.Programa();
    System.out.println("Compilado....");
  }
  catch(TokenMgrError e) {
  System.err.println("Lexical Error:\n" + e.getMessage());
  }
  catch(ParseException e) {
  System.err.println("Syntactic Error:\n" + e.getMessage());
  }
  catch(Exception e) {
  System.err.println("Semantic error:\n" + e.getMessage()  );
  e.printStackTrace();
  }
 }

//////////////////////////////////////INICIO//////////////////////////////
  final public void Programa() throws ParseException {
    jj_consume_token(INICIO);
    Variaveis();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case FOR:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      Comandos(true);
    }
    jj_consume_token(FIM);
    jj_consume_token(0);
Tabela.imprime();
}

///////////////////////////////////////////////////////////////////////////
  final public void Variaveis() throws ParseException {Token var=null, tipo=null;
    label_2:
    while (true) {
      tipo = jj_consume_token(TIPO);
      var = jj_consume_token(IDENTIFICADOR);
if(tipo.image.equals("BOOL")) Tabela.insere (var.image,"false",tipo.image) ;
    else if(tipo.image.equals("STRING") || tipo.image.equals("CHAR")) Tabela.insere (var.image, null, tipo.image) ;
    else Tabela.insere (var.image, "0" ,tipo.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
    }
}

  final public void Comandos(boolean valida) throws ParseException {
    if (jj_2_1(3)) {
      Atribuicao(valida);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:{
        Condicional(valida);
        break;
        }
      case IDENTIFICADOR:{
        OperacaoTernaria(valida);
        break;
        }
      case FOR:{
        Iterativo(valida);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void Atribuicao(boolean valida) throws ParseException {Token var = null, valor = null, flutuante = null, bool = null, ident = null, string = null, charac = null;
    String result_pesq_tipo_var = "";
    var = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ATRIB);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DIGITO:{
      valor = jj_consume_token(DIGITO);
result_pesq_tipo_var = Tabela.pesquisa_tipo(var.image);
            if(result_pesq_tipo_var.equals("INT") && valida)
                Tabela.insere(var.image, valor.image, "INT");
            else if(valida){
                int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
                System.err.println("Semantic error: Attempted assignment between different types of variable in line " + currentLine + ", Value:" + valor.image);
            }
      break;
      }
    case NUM:{
      flutuante = jj_consume_token(NUM);
result_pesq_tipo_var = Tabela.pesquisa_tipo(var.image);
            if(result_pesq_tipo_var.equals("FLOAT") && valida)
                Tabela.insere(var.image, flutuante.image, "FLOAT");
            else if(result_pesq_tipo_var.equals("DOUBLE") && valida)
                Tabela.insere(var.image, flutuante.image, "DOUBLE");
            else if(valida) {
                int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
                System.err.println("Semantic error: Attempted assignment between different types of variable in line " + currentLine + ", Value:" + flutuante.image);
            }
      break;
      }
    case SENTENCA_BOOLEANA:{
      bool = jj_consume_token(SENTENCA_BOOLEANA);
result_pesq_tipo_var = Tabela.pesquisa_tipo(var.image);
            if(result_pesq_tipo_var.equals("BOOL") && valida)
                Tabela.insere(var.image, bool.image, "BOOL");
            else if(valida){
                int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
                System.err.println("Semantic error: Attempted assignment between different types of variable in line " + currentLine + ", Value:" + bool.image);
            }
      break;
      }
    case IDENTIFICADOR:{
      ident = jj_consume_token(IDENTIFICADOR);
result_pesq_tipo_var = Tabela.pesquisa_tipo(var.image);
            if(result_pesq_tipo_var.equals(Tabela.pesquisa_tipo(ident.image)) && valida){
                Tabela.insere(var.image, Tabela.pesquisa_valor(ident.image), result_pesq_tipo_var);
            }
            else if(valida){
                int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
                System.err.println("Semantic error: Attempted assignment between different types of variable in line " + currentLine + ", Value:" + ident.image);
            }
      break;
      }
    case STRING:{
      string = jj_consume_token(STRING);
result_pesq_tipo_var = Tabela.pesquisa_tipo(var.image);
            if(result_pesq_tipo_var.equals("STRING") && valida){
                Tabela.insere(var.image, string.image, result_pesq_tipo_var);
            }
            else if(valida){
                int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
                System.err.println("Semantic error: Attempted assignment between different types of variable in line " + currentLine + ", Value:" + ident.image);
            }
      break;
      }
    case LETRA:{
      charac = jj_consume_token(LETRA);
result_pesq_tipo_var = Tabela.pesquisa_tipo(var.image);
            if(result_pesq_tipo_var.equals("CHAR") && valida){
                Tabela.insere(var.image, charac.image, result_pesq_tipo_var);
            }
            else if(valida){
                int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
                System.err.println("Semantic error: Attempted assignment between different types of variable in line " + currentLine + ", Value:" + ident.image);
            }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public Token Expressao() throws ParseException {Token var1 = null, var2 = null, op = null, stri = null; double num_a = 0.0, num_b = 0.0; boolean a = false, b = false;
    var1 = fator();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      op = jj_consume_token(OPERADOR);
      var2 = fator();
if(op!=null){
            boolean isNumeric1 = var1.image.matches("[+-]?\\d*(\\.\\d+)?");
            boolean isNumeric2 = var2.image.matches("[+-]?\\d*(\\.\\d+)?");
            if(isNumeric1 && isNumeric2){
                num_a = Double.parseDouble(var1.image);
                num_b = Double.parseDouble(var2.image);
                if(op.image.equals(">")) a = num_a > num_b;
                else if(op.image.equals(">=")) a = num_a >= num_b;
                else if(op.image.equals("<")) a = num_a < num_b;
                else if(op.image.equals("<=")) a = num_a <= num_b;
                else if(op.image.equals("==")) a = num_a == num_b;
                else if(op.image.equals("!=")) a = num_a != num_b;
            }
            else{
                if(op.image.equals("==")) a = var1.image.equals(var2.image);
                else{
                    String str1 = var1.image, str2 = var2.image;
                    int result = str1.compareTo(str2);
                    System.out.println("RESULTADO = "+result);
                    if (result < 0 && op.image.equals("<")) {
                        a = true;
                    } else if (result == 0 && (op.image.equals("<=") || op.image.equals(">=") || op.image.equals("=="))){
                        a = true;
                    } else if(result > 0 && op.image.equals(">")){
                        a = true;
                    }
                    else{
                        a=false;
                    }
                }
            }
        }
        if (a)
            var1.image="true";
        else
            var1.image ="false";
    }
{if ("" != null) return var1;}
    throw new Error("Missing return statement in function");
}

  final public void Condicional(boolean valida) throws ParseException {Token val = null; boolean valida2 = false;
    jj_consume_token(IF);
    jj_consume_token(ABREPA);
    val = Or();
if(val.image.equals("true")) valida2=true;
        else valida2=false;
    jj_consume_token(FECHPA);
    jj_consume_token(THEN);
    jj_consume_token(ABRECH);
    label_4:
    while (true) {
      Comandos(valida2 && valida);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case FOR:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
    }
    jj_consume_token(FECHACH);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(ABRECH);
      label_5:
      while (true) {
        Comandos((!valida2) && valida);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IF:
        case FOR:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_5;
        }
      }
      jj_consume_token(FECHACH);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
}

  final public void OperacaoTernaria(boolean valida) throws ParseException {Token var=null, cond=null, val1=null, val2=null;
    var = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OPERADOR_TERNARIO);
    cond = Expressao();
    jj_consume_token(INTERROGACAO);
    val1 = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(DOIS_PONTOS);
    val2 = jj_consume_token(IDENTIFICADOR);
String varName = var.image;
        if(valida){
        boolean condicao;
        if (cond.image=="true")
            condicao=true;
        else
            condicao=false;
            String valorVerdadeiro = Tabela.pesquisa_valor(val1.image);
            String valorFalso = Tabela.pesquisa_valor(val2.image);

            String resultado = condicao ? valorVerdadeiro : valorFalso;
            Tabela.insere(varName, resultado, Tabela.pesquisa_tipo(varName));
        }
}

  final public Token AndBitwise() throws ParseException {Token tk=null, d=null, r=null, m=null; boolean a=true, b=true;
    tk = Expressao();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ANDB:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_6;
      }
      m = jj_consume_token(ANDB);
      d = Expressao();
if (m!=null){
        if(m.image.equals("&")){
            if(tk.image.equals("true")) a=true;
            else a=false;
            if (d.image.equals("true")) b=true;
            else b=false;
            a = a & b;
        }
    }
    if (a)
    tk.image="true";
    else
    tk.image ="false";
    }
{if ("" != null) return tk;}
    throw new Error("Missing return statement in function");
}

  final public Token xOrBitwise() throws ParseException {Token tk=null, d=null, r=null, m=null; boolean a=true, b=true;
    tk = AndBitwise();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case XOR:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_7;
      }
      m = jj_consume_token(XOR);
      d = AndBitwise();
if (m!=null){
        if(m.image.equals("^")){
            if(tk.image.equals("true")) a=true;
            else a=false;
            if (d.image.equals("true")) b=true;
            else b=false;
            a = a ^ b;
        }
    }
    if (a)
    tk.image="true";
    else
    tk.image ="false";
    }
{if ("" != null) return tk;}
    throw new Error("Missing return statement in function");
}

  final public Token OrBitwise() throws ParseException {Token tk=null, d=null, r=null, m=null; boolean a=true, b=true;
    tk = xOrBitwise();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ORB:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_8;
      }
      m = jj_consume_token(ORB);
      d = xOrBitwise();
if (m!=null){
        if(m.image.equals("|")){
            if(tk.image.equals("true")) a=true;
            else a=false;
            if (d.image.equals("true")) b=true;
            else b=false;
            a = a | b;
        }
    }
    if (a)
    tk.image="true";
    else
    tk.image ="false";
    }
{if ("" != null) return tk;}
    throw new Error("Missing return statement in function");
}

  final public Token And() throws ParseException {Token tk=null, d=null, r=null, m=null; boolean a=true, b=true;
    tk = OrBitwise();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_9;
      }
      m = jj_consume_token(AND);
      d = OrBitwise();
if (m!=null){
        if(m.image.equals("&&")){
            if(tk.image.equals("true")) a=true;
            else a=false;
            if (d.image.equals("true")) b=true;
            else b=false;
            a = a && b;
        }
    }
    if (a)
    tk.image="true";
    else
    tk.image ="false";
    }
{if ("" != null) return tk;}
    throw new Error("Missing return statement in function");
}

  final public Token Or() throws ParseException {Token tk = null, d = null, n = null; boolean a = true, b= true;
    tk = And();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_10;
      }
      n = jj_consume_token(OR);
      d = And();
if (n!=null)
    {
        if(n.image.equals("||")){
            if (tk.image.equals("true"))
                a=true;
            else
                a=false;

            if (d.image.equals("true"))
            b=true;
            else
                b=false;
            a= a || b;
        }
    }
    if (a)
    tk.image="true";
    else
    tk.image="false";
    }
{if ("" != null) return tk;}
    throw new Error("Missing return statement in function");
}

  final public Token fator() throws ParseException {Token num = null, flutuante = null, var = null, bool = null, strings = null, neg = null; String valor = null, tipo = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEGACAO:
    case IDENTIFICADOR:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NEGACAO:{
        neg = jj_consume_token(NEGACAO);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        ;
      }
      var = jj_consume_token(IDENTIFICADOR);
valor = Tabela.pesquisa_valor(var.image);
        if(neg!=null){
            tipo = Tabela.pesquisa_tipo(var.image);
            if(tipo.equals("BOOL")){
                if(var.equals("true")) var.image = "false";
                else var.image = "true";
            }
        }
        else if( valor != "") var.image = valor;
        else{
            System.err.println("Semantic error: value null in variable");
            System.exit(1);
        }
        {if ("" != null) return var;}
      break;
      }
    case DIGITO:{
      num = jj_consume_token(DIGITO);
{if ("" != null) return num;}
      break;
      }
    case NUM:{
      flutuante = jj_consume_token(NUM);
{if ("" != null) return flutuante;}
      break;
      }
    case SENTENCA_BOOLEANA:{
      bool = jj_consume_token(SENTENCA_BOOLEANA);
{if ("" != null) return bool;}
      break;
      }
    case STRING:{
      strings = jj_consume_token(STRING);
{if ("" != null) return strings;}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public void Iterativo(boolean valida) throws ParseException {Token val = null, condi = null, op = null, op2 = null, var1 = null, var2 = null, var3 = null, var4 = null, var5 = null, var6=null, var7=null, var8 = null, operacao = null, var9 = null, numero=null; boolean valida2 = false, a = false; double valor1 = 0.0, valor2 = 0.0;
    jj_consume_token(FOR);
    jj_consume_token(ABREPA);
    Atribuicao(valida);
    jj_consume_token(PONTOVIRGULA);
    var1 = jj_consume_token(IDENTIFICADOR);
    op = jj_consume_token(OPERADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      var2 = jj_consume_token(IDENTIFICADOR);
      break;
      }
    case NUM:{
      var3 = jj_consume_token(NUM);
      break;
      }
    case DIGITO:{
      var3 = jj_consume_token(DIGITO);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PONTOVIRGULA);
    var8 = jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MAISMAIS:{
      operacao = jj_consume_token(MAISMAIS);
      break;
      }
    case SINAL:{
      operacao = jj_consume_token(SINAL);
      jj_consume_token(ATRIB);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUM:{
        numero = jj_consume_token(NUM);
        break;
        }
      case IDENTIFICADOR:{
        var9 = jj_consume_token(IDENTIFICADOR);
        break;
        }
      case DIGITO:{
        numero = jj_consume_token(DIGITO);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(FECHPA);
    jj_consume_token(ABRECH);
    var4 = jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ATRIB);
    var5 = jj_consume_token(IDENTIFICADOR);
    op2 = jj_consume_token(SINAL);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      var6 = jj_consume_token(IDENTIFICADOR);
      break;
      }
    case NUM:{
      var7 = jj_consume_token(NUM);
      break;
      }
    case DIGITO:{
      var7 = jj_consume_token(DIGITO);
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PONTOVIRGULA);
    jj_consume_token(FECHACH);
if(valida){
        if(var2!=null){
          valor2 = Double.parseDouble(Tabela.pesquisa_valor(var2.image));
        }
        else if(var3!=null){
          valor2 = Double.parseDouble(var3.image);
        }
        while (true){
          valor1 = Double.parseDouble(Tabela.pesquisa_valor(var1.image));
          if(op.image.equals(">"))
            a = valor1 > valor2;
          else if (op.image.equals("<"))
            a = valor1 < valor2;
          else if (op.image.equals(">="))
            a= valor1  >= valor2;
          else if (op.image.equals("<="))
            a= valor1  <= valor2;
          else if (op.image.equals("=="))
            a= valor1  == valor2;
          else a = valor1 != valor2;
          if(a==false) break;
          else{
            if(var4.image.equals(var5.image)){
              if(op2.image.equals("+")){
                if(var6==null) Tabela.insere(var4.image, String.valueOf(Double.parseDouble(Tabela.pesquisa_valor(var4.image)) + Double.parseDouble(var7.image)) , Tabela.pesquisa_tipo(var4.image));
                else Tabela.insere(var4.image, String.valueOf(Double.parseDouble(Tabela.pesquisa_valor(var4.image)) + Double.parseDouble(Tabela.pesquisa_valor(var6.image))) , Tabela.pesquisa_tipo(var4.image));
              }
              else{
                if(var6==null) Tabela.insere(var4.image, String.valueOf(Double.parseDouble(Tabela.pesquisa_valor(var4.image)) - Double.parseDouble(var7.image)) , Tabela.pesquisa_tipo(var4.image));
                else Tabela.insere(var4.image, String.valueOf(Double.parseDouble(Tabela.pesquisa_valor(var4.image)) - Double.parseDouble(Tabela.pesquisa_valor(var6.image))) , Tabela.pesquisa_tipo(var4.image));
              }
            }
          }
          Iteracao(true, operacao, var8, numero, var9);
        }
      }
}

  final public void Iteracao(boolean ini,Token operacao, Token var, Token numero, Token var2) throws ParseException {double valor = 0.0;
if(ini){
      valor = Double.parseDouble(Tabela.pesquisa_valor(var.image));
      if(operacao.image.equals("++")){
        valor++;
      }
      else if(operacao.image.equals("--")){
        valor--;
      }
      else if(operacao.image.equals("+")){
        valor = valor + Double.parseDouble(numero.image);
      }
      else if(operacao.image.equals("-")){
        valor = valor - Double.parseDouble(numero.image);
      }
      Tabela.insere(var.image, String.valueOf(valor), Tabela.pesquisa_tipo(var.image));
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_Atribuicao_254_9_17()
 {
    if (jj_scan_token(LETRA)) return true;
    return false;
  }

  private boolean jj_3R_Atribuicao_243_9_16()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_Atribuicao_232_9_15()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_Atribuicao_210_9_13()
 {
    if (jj_scan_token(NUM)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_Atribuicao_198_5_11()) return true;
    return false;
  }

  private boolean jj_3R_Atribuicao_198_5_11()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ATRIB)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Atribuicao_200_9_12()) {
    jj_scanpos = xsp;
    if (jj_3R_Atribuicao_210_9_13()) {
    jj_scanpos = xsp;
    if (jj_3R_Atribuicao_222_9_14()) {
    jj_scanpos = xsp;
    if (jj_3R_Atribuicao_232_9_15()) {
    jj_scanpos = xsp;
    if (jj_3R_Atribuicao_243_9_16()) {
    jj_scanpos = xsp;
    if (jj_3R_Atribuicao_254_9_17()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Atribuicao_222_9_14()
 {
    if (jj_scan_token(SENTENCA_BOOLEANA)) return true;
    return false;
  }

  private boolean jj_3R_Atribuicao_200_9_12()
 {
    if (jj_scan_token(DIGITO)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GramaticaTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[19];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x10060,0x8,0x10060,0x3d8000,0x20000,0x10060,0x10060,0x10,0x800,0x1000,0x200,0x400,0x100,0x2000,0x35a000,0x310000,0x310000,0x0,0x310000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new GramaticaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new GramaticaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new GramaticaTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[38];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 19; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 38; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
